name: Automated API tests using Postman CLI

on:
  workflow_dispatch:
  push:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        id: run-tests
        run: |
          postman collection run "22742638-7b3a5b9a-15a3-4b79-a850-ee18ff361f9d" --report-json output.json
          failures=$(jq '.run.stats.assertions.failed' output.json)
          echo "Failures: $failures"
          if [ "$failures" -le 2 ]; then
            echo "✅ Test run successful with $failures failures (≤ 2 allowed)."
          else
            echo "❌ Too many test failures: $failures"
            exit 1
          fi

      - name: Logout from Postman
        run: postman logout ${{ secrets.POSTMAN_API_KEY }}
